### ISSUE TITLE
[Question] What is the idea of ActivityModule?

### ISSUE THREAD

**Issue by agustinsivoplas** [digitalbuddha/DaggerAndroidViewInjectior#1]
What is the porpuse?

In the past I use this class, but I dont understand in your code what is the reason.

```
@Module
class ActivityModule(private val mActivity: Activity) {

    @Provides
    fun provideActivity(): Activity {
        return mActivity
    }

    @Provides
    @ActivityContext
    fun providesContext(): Context {
        return mActivity
    }
}
```

**Comment by digitalbuddha** [comment]
No purpose, it is just a sample module

**Comment by agustinsivoplas** [comment]
Oh, that was really quick answer. Many thanks. I am new with dagger and I am trying to understand the class I have added in the first answer and if this class apply in your project. 

Another question, I am planning to use the new ViewModel architecture (from Google Architecture Components), So the repositories will be injected in the ViewModel classes, right?  In that case, I should to extend DaggerAppCompatActivity? 
My question is, If I have nothing to Inject in the activity, I should not to extend it. I am a little bit confusing.
